restauranteProfeV2/restaurante/pedidos/urls.py
from django.urls import path
from . import views

app_name = 'pedidos'

urlpatterns = [
    path('', views.inicioSesion,name='inicioSesion'),
    path('panel/', views.panel,name='panel'),
    path('pedidos/<int:id>', views.pedidos,name='pedidos'),
    path('menu/', views.menu,name='menu'),
    path('facturar/', views.facturar,name='facturar'),
    path('salir/', views.salir,name='salir'),
    path('verpedido/<int:id>', views.verpedido ,name='verpedido'),
]

restauranteProfeV2/restaurante/restaurante/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pedidos.urls')),

]

restauranteProfeV2/restaurante/pedidos/models.py
from email.policy import default
from xml.etree.ElementInclude import default_loader
from django.db import models

# Create your models here.


from django.db import models
from django.conf import settings
#from django.contrib.auth.models import User

# Create your models here.

class Informacion(models.Model):
    nombre = models.CharField(max_length=40)
    direccion = models.CharField(max_length=70)
    telefono = models.CharField(max_length=7)
    celular = models.CharField(max_length=10)
    nit = models.CharField(max_length=15)
    representanteLegal = models.CharField(max_length=70)
    eslogan = models.CharField(max_length=150)

    class Meta:
        verbose_name = "Información"
        verbose_name_plural = "Información"
    
    def __str__(self):
        return self.nombre

class Mesa(models.Model):
    numero = models.CharField(max_length=3)
    capacidad = models.IntegerField()
    descripcion = models.TextField()
    estado = models.BooleanField(default=True)
    
    class Meta:
        verbose_name = "Mesas"
        verbose_name_plural = "Mesas"
    
    def __str__(self):
        return f'Mesa {self.numero}'

class Pedido(models.Model):
    mesa = models.ForeignKey(Mesa,on_delete=models.CASCADE)
    mesero = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    fecha = models.DateField()
    hora = models.TimeField()
    estado = models.BooleanField(default=False)

class Tipo_producto(models.Model):
    nombre = models.CharField(max_length=60)
    descripcion = models.TextField()
    estado = models.BooleanField(default=True)

    def __str__(self):
        return self.nombre

class Producto(models.Model):
    nombre = models.CharField(max_length=60)
    tipoProducto = models.ForeignKey(Tipo_producto, on_delete=models.CASCADE)
    precio = models.FloatField()
    numeroPersonas = models.IntegerField()
    descripcion = models.TextField()
    estado = models.BooleanField(default=True)

    def __str__(self):
        return self.nombre

class Producto_pedido(models.Model):
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto,on_delete=models.CASCADE)
    cantidad = models.IntegerField(default=0)
    observacion = models.TextField(default="")

class Factura(models.Model):
    opciones = (
        ("efectivo","Efectivo"),
        ("debito","Tarjeta debito"),
        ("credito","Tarjeta de Crédito"),
        ("transferencia","Transferencia bancaria"),
    )
    pedido = models.ForeignKey(Pedido,on_delete=models.CASCADE)
    fecha = models.DateField()
    hora = models.TimeField()
    valor = models.FloatField()
    medioPago = models.CharField(max_length=20,choices=opciones)
    estado = models.BooleanField()

restauranteProfeV2/restaurante/pedidos/forms.py
from django import forms
from django.forms import Textarea

from .models import Producto


class Credenciales(forms.Form):
    usuario = forms.CharField(label='Usuario',widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Usuario','aria-label':'Usuario'}))
    secreta = forms.CharField(label='Contraseña',widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Contraseña'}))

class form_pedido(forms.Form):
    producto = forms.ModelChoiceField(queryset=Producto.objects.all())
    cantidad = forms.IntegerField()
    observacion = forms.CharField()

restauranteProfeV2/restaurante/pedidos/views.py
import re
from django.http import HttpResponseRedirect
from django.shortcuts import render
from .forms import  Credenciales, form_pedido
from django.contrib.auth import authenticate,logout,login
from  django.views.decorators.cache import never_cache
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Informacion,Mesa,Pedido, Producto, Tipo_producto, Producto_pedido
from datetime import datetime


# Create your views here.

def inicioSesion(request):
    if request.method=="POST":
        form = Credenciales(request.POST)
        if form.is_valid():
            usuario = authenticate(username=form.cleaned_data['usuario'], password=form.cleaned_data['secreta'])
            if usuario is not None:
                login(request,usuario)
                #request.session.set_expiry(1200)
                return HttpResponseRedirect('/panel/')
            else:
                messages.error(request,'Usuario o contraseña incorrecto.')
    else:
        form = Credenciales()
    info = Informacion.objects.get()
    return render(request,'pedidos/inicioSesion.html',{'form':form,'restaurante':info})

@login_required(login_url='/salir/')
@never_cache
def panel(request):
    mesas = Mesa.objects.all().order_by('numero')
    for mesa in mesas:
        print(mesa.estado)
    pedidos = Pedido.objects.all()
    return render(request,'pedidos/panel.html',{'mesas':mesas,'pedidos':pedidos})


@login_required(login_url='/salir/')
@never_cache
def pedidos(request,id):
    mesa = Mesa.objects.get(pk=id)
    if request.method == "POST":
        formpedido = form_pedido(request.POST)
        if formpedido.is_valid():
            if mesa.estado == True:
                ped = Pedido()
                ped.mesa = Mesa.objects.get(pk=id)
                ped.mesero = request.user
                ped.fecha = datetime.today().strftime('%Y-%m-%d')
                ped.hora = datetime.now().strftime('%H:%M:%S')
                ped.estado = False
                ped.save()

                estadomesa = Mesa.objects.get(pk=id)
                estadomesa.estado = False
                estadomesa.save()

            prod_ped = Producto_pedido()
            prod_ped.pedido = Pedido.objects.get(mesa=id, estado=False)
            prod_ped.producto = formpedido.cleaned_data['producto']
            prod_ped.cantidad = formpedido.cleaned_data['cantidad']
            prod_ped.observacion = formpedido.cleaned_data['observacion']
            prod_ped.save()
            
            messages.info(request, "Guardado Correctamente")
        else:
            messages.error(request, "Informacion Invalida")
            print("informacion invalida")
    categorias = Tipo_producto.objects.all()
    formpedido = form_pedido()
    return render(request, 'pedidos/pedido.html', {'categorias':categorias,'formpedido':formpedido})

# hay que buscar el pedido  de la mesa que este en false, ya que una sola mesa puede tener un solo pedido. al momento de cancelar o pagar el pedido este pasa a ser true y se libera la mesa. entonces varios productos pueden pertenecer a un pedido.

@login_required(login_url='/salir/')
@never_cache
def verpedido(request,id):
    verped = Producto_pedido.objects.filter(pedido_id=id)
    return render (request, 'pedidos/verpedido.html', {'verped':verped})


@login_required(login_url='/salir/')
@never_cache
def mesas(request):
    pass

@login_required(login_url='/salir/')
@never_cache
def menu(request):
    pass


@login_required(login_url='/salir/')
@never_cache
def facturar(request):
    pass


def salir(request):
    logout(request)
    return HttpResponseRedirect('/')

restauranteProfeV2/restaurante/pedidos/templates/pedidos/base.html
{%load static%}
<!DOCTYPE html>
<html lang="es">
    <head>
        <title>Restaurante</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Bootstrap -->
        <link href="{%static 'pedidos/bootstrap-5.0.2-dist/css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{%static 'pedidos/css/sidebars.css' %}" rel="stylesheet">
        <script src="{%static 'pedidos/bootstrap-5.0.2-dist/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{%static 'pedidos/js/sidebars.js' %}"></script>
    </head>
    <body>
        <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
          <symbol id="home" viewBox="0 0 16 16">
            <path d="M8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4.5a.5.5 0 0 0 .5-.5v-4h2v4a.5.5 0 0 0 .5.5H14a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146zM2.5 14V7.707l5.5-5.5 5.5 5.5V14H10v-4a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5v4H2.5z"/>
          </symbol>
          <symbol id="currency" viewBox="0 0 16 16">
              <path d="M4 10.781c.148 1.667 1.513 2.85 3.591 3.003V15h1.043v-1.216c2.27-.179 3.678-1.438 3.678-3.3 0-1.59-.947-2.51-2.956-3.028l-.722-.187V3.467c1.122.11 1.879.714 2.07 1.616h1.47c-.166-1.6-1.54-2.748-3.54-2.875V1H7.591v1.233c-1.939.23-3.27 1.472-3.27 3.156 0 1.454.966 2.483 2.661 2.917l.61.162v4.031c-1.149-.17-1.94-.8-2.131-1.718H4zm3.391-3.836c-1.043-.263-1.6-.825-1.6-1.616 0-.944.704-1.641 1.8-1.828v3.495l-.2-.05zm1.591 1.872c1.287.323 1.852.859 1.852 1.769 0 1.097-.826 1.828-2.2 1.939V8.73l.348.086z"/>
          </symbol>
          <symbol id="cart" viewBox="0 0 16 16">
              <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
          </symbol>
          <symbol id="list-columns" viewBox="0 0 16 16">
              <path fill-rule="evenodd" d="M0 .5A.5.5 0 0 1 .5 0h9a.5.5 0 0 1 0 1h-9A.5.5 0 0 1 0 .5Zm13 0a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5Zm-13 2A.5.5 0 0 1 .5 2h8a.5.5 0 0 1 0 1h-8a.5.5 0 0 1-.5-.5Zm13 0a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5Zm-13 2A.5.5 0 0 1 .5 4h10a.5.5 0 0 1 0 1H.5a.5.5 0 0 1-.5-.5Zm13 0a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5Zm-13 2A.5.5 0 0 1 .5 6h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5Zm13 0a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5Zm-13 2A.5.5 0 0 1 .5 8h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5Zm13 0a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5Zm-13 2a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5Zm13 0a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5Zm-13 2a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5Zm13 0a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5Zm-13 2a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H.5a.5.5 0 0 1-.5-.5Zm13 0a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5Z"/>
          </symbol>
      </svg>
      <main>
        <div class="row p-0">
          <div class="d-flex flex-column flex-shrink-0 p-3 text-white bg-dark" style="width: 280px;">
            <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
              <span class="fs-4">La casa de Maria</span>
            </a>
            <hr>
            
            <ul class="nav nav-pills flex-column mb-auto">
              
                <li class="nav-item">
                <a href="#" class="nav-link active" aria-current="page">
                  <svg class="bi me-2" width="16" height="16"><use xlink:href="#home"/></svg>
                  Inicio
                </a>
              </li>
              
              <li>
                <a href="#" class="nav-link text-white">
                  <svg class="bi me-2" width="16" height="16"><use xlink:href="#list-columns"/></svg>
                  Menu
                </a>
              </li>
              
              <li>
                <a href="#" class="nav-link text-white">
                  <svg class="bi me-2" width="16" height="16"><use xlink:href="#cart"/></svg>
                  Pedidos
                </a>
              </li>
              
              <li>
                <a href="#" class="nav-link text-white">
                  <svg class="bi me-2" width="16" height="16"><use xlink:href="#currency"/></svg>
                  Facturacion
                </a>
              </li>
            </ul>
            <hr>
            <div class="dropdown">
              <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2">
                <strong>mdo</strong>
              </a>
              <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
                <li><a class="dropdown-item" href="{% url 'pedidos:salir'%}">Salir</a></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="b-example-divider"></div>  
        <div class="d-flex flex-column p-3 bg-white mx-auto" style="width: 1250px ;" >
          {%block content%}   
          {%endblock%}
        <div>
      </main>
      <footer>
      </footer>
  </body>
</html> 

restauranteProfeV2/restaurante/pedidos/templates/pedidos/inicioSesion.html
{%load static%}
<!DOCTYPE html>
<html lang="es">
    <head>
        <title>Restaurante</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Bootstrap -->
        <link href="{%static 'pedidos/bootstrap-5.0.2-dist/css/bootstrap.min.css' %}" rel="stylesheet">
        <script src="{%static 'pedidos/bootstrap-5.0.2-dist/js/bootstrap.bundle.min.js' %}"></script>
    </head>
    <body>
        <div class="container mt-5">
            <div class="row mt-5 mb-5">
                
                <div class="row ">
                    <div class="col-sm-4 p-3 shadow border rounded-3 bg-dark bg-gradient text-white mx-auto text-center fw-bold">{{restaurante.nombre}}</div>
                </div>
                <div class="row">
                    <div class="col-sm-4 shadow p-4 border rounded-3 mx-auto">
                        <form action="{% url 'pedidos:inicioSesion' %}" method="post">
                            {% csrf_token %}
                            
                            <div class="input-group mb-3">    
                                <span class="input-group-text" id="usuario-addon">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-fill" viewBox="0 0 16 16">
                                        <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                                        </svg>            

                                </span>
                                {{form.usuario}}
                            </div>

                            <div class="input-group mb-3">    
                                <span class="input-group-text" id="contrasena-addon">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-key-fill" viewBox="0 0 16 16">
                                        <path d="M3.5 11.5a3.5 3.5 0 1 1 3.163-5H14L15.5 8 14 9.5l-1-1-1 1-1-1-1 1-1-1-1 1H6.663a3.5 3.5 0 0 1-3.163 2zM2.5 9a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"/>
                                    </svg>            
                                </span>
                                {{form.secreta}}
                            </div>
                            <div class="text-center">
                                <button type="submit" class="btn btn-primary">Entrar</button>
                            </div>
                        </form>
                    </div>
                </div>
                {% if messages %}
                    {% for message in messages%}
                        {%if message.tags == 'error' %}            
                        <div class="row mt-3">
                            <div class="col-sm-4 alert alert-danger mx-auto" role="alert">    
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-exclamation-triangle-fill" viewBox="0 0 16 16">
                                    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                                </svg>
                                <strong>{{message}}</strong>
                            </div>
                        </div>
                        {%endif%}
                    {%endfor%}
                {%endif%}    
            </div>
        </div>
    </body>
</html> 

restauranteProfeV2/restaurante/pedidos/templates/pedidos/panel.html
{% extends 'pedidos/base.html' %}
{%block content%}
    <div class="row">
        {% for mesa in mesas%}

            <div class=" border bg-light m-1" style="width: 300px;height: 200px;">
                {% if mesa.estado == True %}
                    <div class="bg-danger text-white text-center fw-bold">
                        <p>Mesa {{mesa.numero}}</p> 
                    </div>
                    <p>Capacidad: {{mesa.capacidad}}</p>
                    <a href="{% url 'pedidos:pedidos' mesa.id %}">Pedido Nuevo</a>
                {%else%}
                    <div class="bg-success text-white text-center fw-bold">
                        <p>Mesa {{mesa.numero}}</p>
                    </div>
                    <p>Capacidad: {{mesa.capacidad}}</p>
                    {% for pedido in pedidos %}
                        {% if pedido.mesa_id == mesa.id and pedido.estado == False %}
                            <p>Numero Pedido :         
                            <a href="{% url 'pedidos:verpedido' pedido.id %}">{{ pedido.id }}</p></a>
                        {%endif%}    
                    {%endfor%}
                    <a href="{% url 'pedidos:pedidos' mesa.id %}">Agregar mas productos</a>
                   
                {%endif%}
                
            </div>
        {%endfor%}
    </div>
        
{%endblock%}

restauranteProfeV2/restaurante/pedidos/templates/pedidos/pedido.html
{% extends 'pedidos/base.html' %}
{%block content%}

{% for message in messages%}
    {% if message.tags == 'info'%}
        <div class="row mt-3">
            <div class="col-sm-4 mx-auto" role="success">    
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-exclamation-triangle-fill" viewBox="0 0 16 16">
                    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                </svg>
                <strong>{{message}}</strong>
            </div>
        </div>
    {% endif%}
{% endfor %}
    <div class="row">
        <div class="col-sm-4 shadow p-4 border rounded-3 mx-auto">
            <h1>Pedidos</h1>
            <form action="" method="POST">
                {% csrf_token %}
                <div class="input-group mb-3">
                    Producto :{{ formpedido.producto }}
                </div>
                <div class="input-group mb-3">
                    Cantidad : {{ formpedido.cantidad }}
                </div>
                    <div class="input-group mb-3">
                    Observacion : {{ formpedido.observacion }}
                </div>
                <div class="text-center">
                    <button type="submit" class="btn btn-primary">Registrar</button>
                    <a href="/panel" class="btn btn-primary">Terminar Pedido</a>
                </div>
            </form>
        </div>
    </div>
        
{%endblock%}

restauranteProfeV2/restaurante/pedidos/templates/pedidos/verpedido.html
{% extends 'pedidos/base.html' %}
{%block content%}
    <div class="row">
        <div class="col-sm-6 shadow p-4 border rounded-3 mx-auto">
            <div class="col-md-6 mx-auto">
                <h1>Ver Pedido</h1>
            </div>
            
            <div class="row">
                <div class="col-md-4">
                    <h3>Productos</h3>
                </div>
                <div class="col-md-3">
                    <h3>Cantidad</h3>
                </div>
                <div class="col-md-5">
                    <h3>Observacion</h3>
                </div>
            </div>
            {% for pedido in verped %}
                    <div class="row">
                        <div class="col-md-4">
                            {{ pedido.producto }}
                        </div>
                        <div class="col-md-3">
                            {{ pedido.cantidad }}
                        </div>
                        <div class="col-md-5">
                            {{ pedido.observacion }}
                        </div>
                    </div>
            {% endfor %}
            <br>
            <div class="col-md-4  mx-auto">
                <a href="/panel" class="btn btn-primary">Regresar</a>
            </div>
        </div>
    </div>
        
{%endblock%}